/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tv_chushou_basis_rtmp_JniUtils */

#ifndef _Included_tv_chushou_basis_rtmp_JniUtils
#define _Included_tv_chushou_basis_rtmp_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tv_chushou_basis_rtmp_JniUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tv_chushou_basis_rtmp_JniUtils_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
