/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cradle_rancune_learningandroid_jni_JniUtils */

#ifndef _Included_cradle_rancune_learningandroid_jni_JniUtils
#define _Included_cradle_rancune_learningandroid_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cradle_rancune_learningandroid_jni_JniUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cradle_rancune_learningandroid_jni_JniUtils_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     cradle_rancune_learningandroid_jni_JniUtils
 * Method:    addNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cradle_rancune_learningandroid_jni_JniUtils_addNum
  (JNIEnv *, jobject);

/*
 * Class:     cradle_rancune_learningandroid_jni_JniUtils
 * Method:    setNormalField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cradle_rancune_learningandroid_jni_JniUtils_setNormalField
  (JNIEnv *, jobject);

/*
 * Class:     cradle_rancune_learningandroid_jni_JniUtils
 * Method:    setStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cradle_rancune_learningandroid_jni_JniUtils_setStaticField
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
